In [ ]:
import pandas as pd
import requests
import pandas as pd
from scipy.stats import pearsonr

df=pd.read_csv("..\\data\\cleaned\\cleaned_sale_properties.csv")

non_empty_epc_df = df[df["epc"].notna()].count()

print (non_empty_epc_df)

#TO get to know most outliners
min_max = pd.DataFrame({
    'min': df.min(),
    'max': df.max()
})
with pd.option_context(
    'display.max_rows', None,
    'display.max_columns', None,
    'display.max_colwidth', None
):
    display(min_max)


# to check duplicate based on same  location , price and surface


duplicates = df.duplicated(
    subset=[ 'latitude', 'longitude','price','livable_surface','land_surface']
).sum()

print(f"Duplicate rows: {duplicates}")


duplicated_rows = df.copy()

duplicated_rows['duplicate_count'] = (
    duplicated_rows.groupby(['latitude', 'longitude','price','livable_surface','land_surface'])
    .transform('size')
)

duplicated_rows = duplicated_rows[
    duplicated_rows['duplicate_count'] > 1
].sort_values(['latitude', 'longitude','price','livable_surface','land_surface'])

duplicated_rows.to_csv(
    'duplicate_new_summary.csv',
    index=False,
    encoding='utf-8-sig'
)
display(duplicated_rows)

property_id                   9672
posting_date                  9672
property_type                 9672
category                      9672
transaction_type              9672
new_construction              9672
price                         9672
price_per_sqm                 9255
cadastral_income              4450
street                        7650
postal_code                   9672
locality                      9672
province                      9672
region                        9672
latitude                      9672
longitude                     9672
bedrooms                      9455
livable_surface               9672
kitchen_equipment             3431
bathrooms                     8706
toilets                       7005
build_year                    6334
furnished                     5947
heating_type                  6569
glazing_type                  5689
solar_panels                  1346
air_conditioning              2087
primary_energy_consumption    9603
epc                           9672
electrical_certificate        7882
facades                       7478
facade_orientation            3352
garden                        6930
garden_surface                2259
garden_orientation             657
terrace                       7979
terrace_surface               4479
balcony                        804
garage                        4152
garages                       3337
indoor_parking                1673
outdoor_parking               2330
cellar                        3541
swimming_pool                 2337
elevator                      7693
running_water                 5068
flooding_area_type            5363
flood_g_score                 1479
flood_p_score                 1461
availability                  5273
building_state                7992
land_surface                  4318
number_of_floors              5493
apartment_floor               4077
maintenance_cost               503
nearest_city                  9672
nearest_city_distance_km      9672
certain_parking_space         3335
has_parking                   9672
dtype: int64

                                        min                     max
property_id                        rah80542                vwd17821
posting_date                     2018-04-04              2026-06-12
property_type                      bungalow                   villa
category                          apartment                   house
transaction_type                   for-sale                for-sale
new_construction                        0.0                     1.0
price                                   0.0              13000000.0
price_per_sqm                           0.0               1620000.0
cadastral_income                        1.0                190501.0
street                         's Herenbaan      ÉMILE JACQMAINLAAN
postal_code                          1000.0                  9991.0
locality                            Aalbeke                  Étalle
province                            Antwerp           West Flanders
region                             Brussels                Wallonia
latitude                           2.928656                51.47244
longitude                          2.509162                51.34635
bedrooms                                0.0                   100.0
livable_surface                         0.0                  9762.0
kitchen_equipment            Fully equipped          Super equipped
bathrooms                               1.0                    71.0
toilets                                 1.0                    32.0
build_year                           1577.0                  2028.0
furnished                               0.0                     1.0
heating_type                           Coal                    Wood
glazing_type                   Double glass            Triple glass
solar_panels                            0.0                     1.0
air_conditioning                        0.0                     1.0
primary_energy_consumption            -52.0              20260607.0
epc                                       A                       G
electrical_certificate                  0.0                     1.0
facades                                 1.0                     8.0
facade_orientation                     East                    West
garden                                  0.0                     1.0
garden_surface                          1.0                150000.0
garden_orientation                     East                    West
terrace                                 0.0                     1.0
terrace_surface                         1.0                  2968.0
balcony                                 0.0                     1.0
garage                                  1.0                     1.0
garages                                 1.0                   130.0
indoor_parking                          1.0                  2020.0
outdoor_parking                         1.0                  1000.0
cellar                                  0.0                     1.0
swimming_pool                           0.0                     1.0
elevator                                0.0                     1.0
running_water                           0.0                     1.0
flooding_area_type                 Low risk  possible flooding area
flood_g_score                             A                       D
flood_p_score                             A                       D
availability                From 01/01/2027             On contract
building_state                    Excellent      Under construction
land_surface                            2.0                178367.0
number_of_floors                        1.0                    41.0
apartment_floor                         0.0                   999.0
maintenance_cost                        1.0                  3000.0
nearest_city                    Aachen (DE)                Verviers
nearest_city_distance_km               0.01                 6702.34
certain_parking_space                  True                    True
has_parking                           False                    True

Duplicate rows: 0

Empty DataFrame
Columns: [property_id, posting_date, property_type, category, transaction_type, new_construction, price, price_per_sqm, cadastral_income, street, postal_code, locality, province, region, latitude, longitude, bedrooms, livable_surface, kitchen_equipment, bathrooms, toilets, build_year, furnished, heating_type, glazing_type, solar_panels, air_conditioning, primary_energy_consumption, epc, electrical_certificate, facades, facade_orientation, garden, garden_surface, garden_orientation, terrace, terrace_surface, balcony, garage, garages, indoor_parking, outdoor_parking, cellar, swimming_pool, elevator, running_water, flooding_area_type, flood_g_score, flood_p_score, availability, building_state, land_surface, number_of_floors, apartment_floor, maintenance_cost, nearest_city, nearest_city_distance_km, certain_parking_space, has_parking, duplicate_count]
Index: []

[0 rows x 60 columns]